const sumar = require('./sumar')
const restar = require('./restar')
const dividir = require('./dividir')
const multiplicar = require('./multiplicar')

console.log(sumar(2, 2))
console.log(restar(3, 2))
console.log(multiplicar(2, 2))
console.log(multiplicar(0, 2))
console.log(dividir(10, 2))
console.log(dividir(0, 0))